# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control_usb.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Preferences(object):
    def setupUi(self, Preferences):
        Preferences.setObjectName("Preferences")
        Preferences.resize(900, 766)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Preferences.sizePolicy().hasHeightForWidth())
        Preferences.setSizePolicy(sizePolicy)
        Preferences.setMinimumSize(QtCore.QSize(900, 766))
        Preferences.setMaximumSize(QtCore.QSize(900, 766))
        Preferences.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(Preferences)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_8 = QtWidgets.QWidget(self.centralwidget)
        self.widget_8.setGeometry(QtCore.QRect(490, 620, 401, 91))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget_8.setPalette(palette)
        self.widget_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.widget_8.setWhatsThis("")
        self.widget_8.setAutoFillBackground(True)
        self.widget_8.setObjectName("widget_8")
        self.Save = QtWidgets.QPushButton(self.widget_8)
        self.Save.setGeometry(QtCore.QRect(10, 50, 181, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(148, 148, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Save.setPalette(palette)
        self.Save.setWhatsThis("")
        self.Save.setDefault(False)
        self.Save.setFlat(False)
        self.Save.setObjectName("Save")
        self.Refresh = QtWidgets.QPushButton(self.widget_8)
        self.Refresh.setGeometry(QtCore.QRect(270, 10, 121, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(148, 148, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Refresh.setPalette(palette)
        self.Refresh.setWhatsThis("")
        self.Refresh.setDefault(False)
        self.Refresh.setFlat(False)
        self.Refresh.setObjectName("Refresh")
        self.Load_Preset = QtWidgets.QPushButton(self.widget_8)
        self.Load_Preset.setGeometry(QtCore.QRect(10, 10, 121, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(148, 148, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Load_Preset.setPalette(palette)
        self.Load_Preset.setWhatsThis("")
        self.Load_Preset.setDefault(False)
        self.Load_Preset.setFlat(False)
        self.Load_Preset.setObjectName("Load_Preset")
        self.Quit = QtWidgets.QPushButton(self.widget_8)
        self.Quit.setGeometry(QtCore.QRect(210, 50, 181, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(148, 148, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Quit.setPalette(palette)
        self.Quit.setWhatsThis("")
        self.Quit.setDefault(False)
        self.Quit.setFlat(False)
        self.Quit.setObjectName("Quit")
        self.Save_Preset = QtWidgets.QPushButton(self.widget_8)
        self.Save_Preset.setGeometry(QtCore.QRect(140, 10, 121, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(148, 148, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Save_Preset.setPalette(palette)
        self.Save_Preset.setWhatsThis("")
        self.Save_Preset.setDefault(False)
        self.Save_Preset.setFlat(False)
        self.Save_Preset.setObjectName("Save_Preset")
        self.widget_9 = QtWidgets.QWidget(self.centralwidget)
        self.widget_9.setGeometry(QtCore.QRect(20, 690, 401, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget_9.setPalette(palette)
        self.widget_9.setAutoFillBackground(True)
        self.widget_9.setObjectName("widget_9")
        self.label_25 = QtWidgets.QLabel(self.widget_9)
        self.label_25.setGeometry(QtCore.QRect(110, 0, 181, 16))
        self.label_25.setObjectName("label_25")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(180, 330, 81, 21))
        self.label_19.setObjectName("label_19")
        self.widget_6 = QtWidgets.QWidget(self.centralwidget)
        self.widget_6.setGeometry(QtCore.QRect(20, 360, 401, 121))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget_6.setPalette(palette)
        self.widget_6.setAutoFillBackground(True)
        self.widget_6.setObjectName("widget_6")
        self.spinBox_14 = QtWidgets.QSpinBox(self.widget_6)
        self.spinBox_14.setGeometry(QtCore.QRect(330, 90, 61, 24))
        self.spinBox_14.setFrame(False)
        self.spinBox_14.setMaximum(127)
        self.spinBox_14.setProperty("value", 127)
        self.spinBox_14.setObjectName("spinBox_14")
        self.spinBox_12 = QtWidgets.QSpinBox(self.widget_6)
        self.spinBox_12.setGeometry(QtCore.QRect(330, 10, 61, 24))
        self.spinBox_12.setFrame(False)
        self.spinBox_12.setMinimum(1)
        self.spinBox_12.setMaximum(8)
        self.spinBox_12.setProperty("value", 1)
        self.spinBox_12.setObjectName("spinBox_12")
        self.label_17 = QtWidgets.QLabel(self.widget_6)
        self.label_17.setGeometry(QtCore.QRect(10, 50, 41, 20))
        self.label_17.setObjectName("label_17")
        self.spinBox_13 = QtWidgets.QSpinBox(self.widget_6)
        self.spinBox_13.setGeometry(QtCore.QRect(330, 50, 61, 24))
        self.spinBox_13.setFrame(False)
        self.spinBox_13.setMinimum(1)
        self.spinBox_13.setMaximum(50)
        self.spinBox_13.setProperty("value", 1)
        self.spinBox_13.setObjectName("spinBox_13")
        self.LED_Speed_Slider = QtWidgets.QSlider(self.widget_6)
        self.LED_Speed_Slider.setGeometry(QtCore.QRect(140, 50, 160, 22))
        self.LED_Speed_Slider.setMinimum(1)
        self.LED_Speed_Slider.setMaximum(50)
        self.LED_Speed_Slider.setProperty("value", 1)
        self.LED_Speed_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.LED_Speed_Slider.setObjectName("LED_Speed_Slider")
        self.LED_Bright_Slider = QtWidgets.QSlider(self.widget_6)
        self.LED_Bright_Slider.setGeometry(QtCore.QRect(140, 90, 160, 22))
        self.LED_Bright_Slider.setMaximum(127)
        self.LED_Bright_Slider.setProperty("value", 127)
        self.LED_Bright_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.LED_Bright_Slider.setObjectName("LED_Bright_Slider")
        self.label_16 = QtWidgets.QLabel(self.widget_6)
        self.label_16.setGeometry(QtCore.QRect(10, 10, 101, 20))
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(self.widget_6)
        self.label_18.setGeometry(QtCore.QRect(10, 90, 71, 21))
        self.label_18.setObjectName("label_18")
        self.LED_Prog_Slider = QtWidgets.QSlider(self.widget_6)
        self.LED_Prog_Slider.setGeometry(QtCore.QRect(140, 10, 160, 22))
        self.LED_Prog_Slider.setMinimum(1)
        self.LED_Prog_Slider.setMaximum(8)
        self.LED_Prog_Slider.setProperty("value", 1)
        self.LED_Prog_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.LED_Prog_Slider.setObjectName("LED_Prog_Slider")
        self.widget_10 = QtWidgets.QWidget(self.centralwidget)
        self.widget_10.setGeometry(QtCore.QRect(20, 40, 871, 281))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget_10.setPalette(palette)
        self.widget_10.setAutoFillBackground(True)
        self.widget_10.setObjectName("widget_10")
        self.Pot_4 = QtWidgets.QDial(self.widget_10)
        self.Pot_4.setGeometry(QtCore.QRect(530, 30, 171, 101))
        self.Pot_4.setMaximum(127)
        self.Pot_4.setProperty("value", 25)
        self.Pot_4.setObjectName("Pot_4")
        self.spinBox_6 = QtWidgets.QSpinBox(self.widget_10)
        self.spinBox_6.setGeometry(QtCore.QRect(600, 130, 48, 24))
        self.spinBox_6.setMaximum(127)
        self.spinBox_6.setProperty("value", 25)
        self.spinBox_6.setObjectName("spinBox_6")
        self.Super_Sonic_Right = QtWidgets.QSlider(self.widget_10)
        self.Super_Sonic_Right.setGeometry(QtCore.QRect(740, 20, 121, 22))
        self.Super_Sonic_Right.setMaximum(127)
        self.Super_Sonic_Right.setProperty("value", 27)
        self.Super_Sonic_Right.setOrientation(QtCore.Qt.Horizontal)
        self.Super_Sonic_Right.setObjectName("Super_Sonic_Right")
        self.spinBox_2 = QtWidgets.QSpinBox(self.widget_10)
        self.spinBox_2.setGeometry(QtCore.QRect(690, 20, 48, 24))
        self.spinBox_2.setMaximum(127)
        self.spinBox_2.setProperty("value", 27)
        self.spinBox_2.setObjectName("spinBox_2")
        self.Pot_5 = QtWidgets.QDial(self.widget_10)
        self.Pot_5.setGeometry(QtCore.QRect(760, 160, 111, 81))
        self.Pot_5.setMaximum(127)
        self.Pot_5.setProperty("value", 23)
        self.Pot_5.setObjectName("Pot_5")
        self.spinBox_7 = QtWidgets.QSpinBox(self.widget_10)
        self.spinBox_7.setGeometry(QtCore.QRect(800, 240, 48, 24))
        self.spinBox_7.setMaximum(127)
        self.spinBox_7.setProperty("value", 23)
        self.spinBox_7.setObjectName("spinBox_7")
        self.Pot_3 = QtWidgets.QDial(self.widget_10)
        self.Pot_3.setGeometry(QtCore.QRect(410, 190, 71, 51))
        self.Pot_3.setMaximum(127)
        self.Pot_3.setProperty("value", 24)
        self.Pot_3.setObjectName("Pot_3")
        self.spinBox_5 = QtWidgets.QSpinBox(self.widget_10)
        self.spinBox_5.setGeometry(QtCore.QRect(430, 240, 48, 24))
        self.spinBox_5.setMaximum(127)
        self.spinBox_5.setProperty("value", 24)
        self.spinBox_5.setObjectName("spinBox_5")
        self.spinBox_4 = QtWidgets.QSpinBox(self.widget_10)
        self.spinBox_4.setGeometry(QtCore.QRect(40, 250, 48, 24))
        self.spinBox_4.setMaximum(127)
        self.spinBox_4.setProperty("value", 21)
        self.spinBox_4.setObjectName("spinBox_4")
        self.Pot_1 = QtWidgets.QDial(self.widget_10)
        self.Pot_1.setGeometry(QtCore.QRect(0, 160, 111, 81))
        self.Pot_1.setMaximum(127)
        self.Pot_1.setProperty("value", 21)
        self.Pot_1.setObjectName("Pot_1")
        self.Pot_2 = QtWidgets.QDial(self.widget_10)
        self.Pot_2.setGeometry(QtCore.QRect(190, 30, 171, 101))
        self.Pot_2.setMaximum(127)
        self.Pot_2.setProperty("value", 20)
        self.Pot_2.setObjectName("Pot_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.widget_10)
        self.spinBox_3.setGeometry(QtCore.QRect(260, 130, 48, 24))
        self.spinBox_3.setMaximum(127)
        self.spinBox_3.setProperty("value", 20)
        self.spinBox_3.setObjectName("spinBox_3")
        self.Super_Sonic_Left = QtWidgets.QSlider(self.widget_10)
        self.Super_Sonic_Left.setGeometry(QtCore.QRect(20, 20, 121, 22))
        self.Super_Sonic_Left.setMaximum(127)
        self.Super_Sonic_Left.setProperty("value", 26)
        self.Super_Sonic_Left.setOrientation(QtCore.Qt.Horizontal)
        self.Super_Sonic_Left.setObjectName("Super_Sonic_Left")
        self.spinBox = QtWidgets.QSpinBox(self.widget_10)
        self.spinBox.setGeometry(QtCore.QRect(160, 20, 48, 24))
        self.spinBox.setMaximum(127)
        self.spinBox.setProperty("value", 26)
        self.spinBox.setObjectName("spinBox")
        self.label_22 = QtWidgets.QLabel(self.widget_10)
        self.label_22.setGeometry(QtCore.QRect(30, 50, 151, 21))
        self.label_22.setObjectName("label_22")
        self.COM_Ports = QtWidgets.QLabel(self.widget_10)
        self.COM_Ports.setGeometry(QtCore.QRect(340, 90, 211, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 22, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 22, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.COM_Ports.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(31)
        self.COM_Ports.setFont(font)
        self.COM_Ports.setObjectName("COM_Ports")
        self.label_26 = QtWidgets.QLabel(self.widget_10)
        self.label_26.setGeometry(QtCore.QRect(700, 50, 161, 21))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.widget_10)
        self.label_27.setGeometry(QtCore.QRect(50, 147, 21, 21))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.widget_10)
        self.label_28.setGeometry(QtCore.QRect(270, 20, 21, 21))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.widget_10)
        self.label_29.setGeometry(QtCore.QRect(440, 176, 21, 21))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.widget_10)
        self.label_30.setGeometry(QtCore.QRect(610, 20, 21, 21))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.widget_10)
        self.label_31.setGeometry(QtCore.QRect(810, 150, 21, 21))
        self.label_31.setObjectName("label_31")
        self.Connecting = QtWidgets.QLabel(self.widget_10)
        self.Connecting.setGeometry(QtCore.QRect(410, 140, 81, 21))
        self.Connecting.setObjectName("Connecting")
        self.widget_11 = QtWidgets.QWidget(self.centralwidget)
        self.widget_11.setGeometry(QtCore.QRect(20, 520, 401, 91))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget_11.setPalette(palette)
        self.widget_11.setAutoFillBackground(True)
        self.widget_11.setObjectName("widget_11")
        self.spinBox_15 = QtWidgets.QSpinBox(self.widget_11)
        self.spinBox_15.setGeometry(QtCore.QRect(330, 10, 61, 24))
        self.spinBox_15.setFrame(False)
        self.spinBox_15.setMinimum(1)
        self.spinBox_15.setMaximum(16)
        self.spinBox_15.setProperty("value", 1)
        self.spinBox_15.setObjectName("spinBox_15")
        self.MIDI_Channel_Slider = QtWidgets.QSlider(self.widget_11)
        self.MIDI_Channel_Slider.setGeometry(QtCore.QRect(140, 10, 160, 22))
        self.MIDI_Channel_Slider.setMinimum(1)
        self.MIDI_Channel_Slider.setMaximum(16)
        self.MIDI_Channel_Slider.setProperty("value", 1)
        self.MIDI_Channel_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.MIDI_Channel_Slider.setObjectName("MIDI_Channel_Slider")
        self.label_20 = QtWidgets.QLabel(self.widget_11)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 101, 20))
        self.label_20.setObjectName("label_20")
        self.label_32 = QtWidgets.QLabel(self.widget_11)
        self.label_32.setGeometry(QtCore.QRect(10, 60, 101, 20))
        self.label_32.setObjectName("label_32")
        self.Latency_Slider = QtWidgets.QSlider(self.widget_11)
        self.Latency_Slider.setGeometry(QtCore.QRect(140, 60, 160, 22))
        self.Latency_Slider.setMinimum(5)
        self.Latency_Slider.setMaximum(50)
        self.Latency_Slider.setProperty("value", 5)
        self.Latency_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Latency_Slider.setObjectName("Latency_Slider")
        self.spinBox_16 = QtWidgets.QSpinBox(self.widget_11)
        self.spinBox_16.setGeometry(QtCore.QRect(330, 60, 61, 24))
        self.spinBox_16.setFrame(False)
        self.spinBox_16.setMinimum(5)
        self.spinBox_16.setMaximum(50)
        self.spinBox_16.setProperty("value", 5)
        self.spinBox_16.setObjectName("spinBox_16")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(170, 490, 141, 21))
        self.label_21.setObjectName("label_21")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(390, 10, 141, 21))
        self.label_23.setObjectName("label_23")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(490, 360, 401, 121))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget_3.setPalette(palette)
        self.widget_3.setAutoFillBackground(True)
        self.widget_3.setObjectName("widget_3")
        self.Smooth_label = QtWidgets.QLabel(self.widget_3)
        self.Smooth_label.setGeometry(QtCore.QRect(10, 90, 71, 20))
        self.Smooth_label.setObjectName("Smooth_label")
        self.Smooth_Slider = QtWidgets.QSlider(self.widget_3)
        self.Smooth_Slider.setGeometry(QtCore.QRect(140, 90, 160, 22))
        self.Smooth_Slider.setMouseTracking(True)
        self.Smooth_Slider.setTabletTracking(True)
        self.Smooth_Slider.setMaximum(5)
        self.Smooth_Slider.setProperty("value", 0)
        self.Smooth_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Smooth_Slider.setObjectName("Smooth_Slider")
        self.Distance_min_label = QtWidgets.QLabel(self.widget_3)
        self.Distance_min_label.setGeometry(QtCore.QRect(10, 10, 81, 20))
        self.Distance_min_label.setObjectName("Distance_min_label")
        self.Distance_min_Slider = QtWidgets.QSlider(self.widget_3)
        self.Distance_min_Slider.setGeometry(QtCore.QRect(140, 10, 160, 22))
        self.Distance_min_Slider.setMouseTracking(True)
        self.Distance_min_Slider.setTabletTracking(True)
        self.Distance_min_Slider.setMaximum(2000)
        self.Distance_min_Slider.setSingleStep(1)
        self.Distance_min_Slider.setProperty("value", 150)
        self.Distance_min_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Distance_min_Slider.setObjectName("Distance_min_Slider")
        self.Distance_max_Slider = QtWidgets.QSlider(self.widget_3)
        self.Distance_max_Slider.setGeometry(QtCore.QRect(140, 50, 160, 22))
        self.Distance_max_Slider.setMouseTracking(True)
        self.Distance_max_Slider.setTabletTracking(True)
        self.Distance_max_Slider.setMaximum(2500)
        self.Distance_max_Slider.setProperty("value", 1200)
        self.Distance_max_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Distance_max_Slider.setObjectName("Distance_max_Slider")
        self.Distance_max_label = QtWidgets.QLabel(self.widget_3)
        self.Distance_max_label.setGeometry(QtCore.QRect(10, 50, 81, 20))
        self.Distance_max_label.setObjectName("Distance_max_label")
        self.spinBox_8 = QtWidgets.QSpinBox(self.widget_3)
        self.spinBox_8.setGeometry(QtCore.QRect(330, 90, 61, 24))
        self.spinBox_8.setFrame(False)
        self.spinBox_8.setMaximum(5)
        self.spinBox_8.setProperty("value", 0)
        self.spinBox_8.setObjectName("spinBox_8")
        self.spinBox_10 = QtWidgets.QSpinBox(self.widget_3)
        self.spinBox_10.setGeometry(QtCore.QRect(330, 10, 61, 24))
        self.spinBox_10.setFrame(False)
        self.spinBox_10.setMaximum(2500)
        self.spinBox_10.setProperty("value", 150)
        self.spinBox_10.setObjectName("spinBox_10")
        self.spinBox_11 = QtWidgets.QSpinBox(self.widget_3)
        self.spinBox_11.setGeometry(QtCore.QRect(330, 50, 61, 24))
        self.spinBox_11.setFrame(False)
        self.spinBox_11.setMaximum(2500)
        self.spinBox_11.setProperty("value", 1200)
        self.spinBox_11.setObjectName("spinBox_11")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(630, 330, 121, 16))
        self.label_5.setObjectName("label_5")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(630, 490, 111, 20))
        self.label_12.setObjectName("label_12")
        self.widget_7 = QtWidgets.QWidget(self.centralwidget)
        self.widget_7.setGeometry(QtCore.QRect(490, 520, 401, 58))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget_7.setPalette(palette)
        self.widget_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.widget_7.setMouseTracking(False)
        self.widget_7.setAutoFillBackground(True)
        self.widget_7.setObjectName("widget_7")
        self.SuperSonic_R_Button = QtWidgets.QPushButton(self.widget_7)
        self.SuperSonic_R_Button.setGeometry(QtCore.QRect(140, 10, 121, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(148, 148, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.SuperSonic_R_Button.setPalette(palette)
        self.SuperSonic_R_Button.setWhatsThis("")
        self.SuperSonic_R_Button.setCheckable(True)
        self.SuperSonic_R_Button.setChecked(True)
        self.SuperSonic_R_Button.setFlat(False)
        self.SuperSonic_R_Button.setObjectName("SuperSonic_R_Button")
        self.SuperSonic_L_Button = QtWidgets.QPushButton(self.widget_7)
        self.SuperSonic_L_Button.setGeometry(QtCore.QRect(10, 10, 121, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 241, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 117, 118))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(157, 156, 157))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 241, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 117, 118))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(157, 156, 157))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 117, 118))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 241, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 117, 118))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(157, 156, 157))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 117, 118))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 117, 118))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 235, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.SuperSonic_L_Button.setPalette(palette)
        self.SuperSonic_L_Button.setStatusTip("")
        self.SuperSonic_L_Button.setWhatsThis("")
        self.SuperSonic_L_Button.setAutoFillBackground(False)
        self.SuperSonic_L_Button.setCheckable(True)
        self.SuperSonic_L_Button.setChecked(True)
        self.SuperSonic_L_Button.setFlat(False)
        self.SuperSonic_L_Button.setObjectName("SuperSonic_L_Button")
        self.Potentiometrs = QtWidgets.QPushButton(self.widget_7)
        self.Potentiometrs.setGeometry(QtCore.QRect(270, 10, 121, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(148, 148, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Potentiometrs.setPalette(palette)
        self.Potentiometrs.setWhatsThis("")
        self.Potentiometrs.setCheckable(True)
        self.Potentiometrs.setChecked(True)
        self.Potentiometrs.setFlat(False)
        self.Potentiometrs.setObjectName("Potentiometrs")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(650, 590, 71, 20))
        self.label_24.setObjectName("label_24")
        self.widget_10.raise_()
        self.widget_8.raise_()
        self.widget_9.raise_()
        self.label_19.raise_()
        self.widget_6.raise_()
        self.widget_11.raise_()
        self.label_21.raise_()
        self.label_23.raise_()
        self.widget_3.raise_()
        self.label_5.raise_()
        self.label_12.raise_()
        self.widget_7.raise_()
        self.label_24.raise_()
        Preferences.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Preferences)
        self.statusbar.setObjectName("statusbar")
        Preferences.setStatusBar(self.statusbar)
        self.actionControllers_Setup = QtWidgets.QAction(Preferences)
        self.actionControllers_Setup.setObjectName("actionControllers_Setup")

        self.retranslateUi(Preferences)
        self.Pot_1.valueChanged['int'].connect(self.spinBox_4.setValue)
        self.spinBox_4.valueChanged['int'].connect(self.Pot_1.setValue)
        self.Pot_2.valueChanged['int'].connect(self.spinBox_3.setValue)
        self.spinBox_3.valueChanged['int'].connect(self.Pot_2.setValue)
        self.Super_Sonic_Left.valueChanged['int'].connect(self.spinBox.setValue)
        self.spinBox.valueChanged['int'].connect(self.Super_Sonic_Left.setValue)
        self.spinBox_2.valueChanged['int'].connect(self.Super_Sonic_Right.setValue)
        self.Pot_4.valueChanged['int'].connect(self.spinBox_6.setValue)
        self.spinBox_6.valueChanged['int'].connect(self.Pot_4.setValue)
        self.Pot_3.valueChanged['int'].connect(self.spinBox_5.setValue)
        self.spinBox_5.valueChanged['int'].connect(self.Pot_3.setValue)
        self.Pot_5.valueChanged['int'].connect(self.spinBox_7.setValue)
        self.spinBox_7.valueChanged['int'].connect(self.Pot_5.setValue)
        self.LED_Prog_Slider.valueChanged['int'].connect(self.spinBox_12.setValue)
        self.spinBox_12.valueChanged['int'].connect(self.LED_Prog_Slider.setValue)
        self.MIDI_Channel_Slider.valueChanged['int'].connect(self.spinBox_15.setValue)
        self.spinBox_15.valueChanged['int'].connect(self.MIDI_Channel_Slider.setValue)
        self.LED_Speed_Slider.valueChanged['int'].connect(self.spinBox_13.setValue)
        self.spinBox_13.valueChanged['int'].connect(self.LED_Speed_Slider.setValue)
        self.LED_Bright_Slider.valueChanged['int'].connect(self.spinBox_14.setValue)
        self.spinBox_14.valueChanged['int'].connect(self.LED_Bright_Slider.setValue)
        self.spinBox_2.valueChanged['int'].connect(self.Super_Sonic_Right.setValue)
        self.Pot_4.valueChanged['int'].connect(self.Pot_4.setValue)
        self.Pot_4.valueChanged['int'].connect(self.spinBox_6.setValue)
        self.Super_Sonic_Right.valueChanged['int'].connect(self.spinBox_2.setValue)
        self.spinBox_16.valueChanged['int'].connect(self.Latency_Slider.setValue)
        self.Latency_Slider.valueChanged['int'].connect(self.spinBox_16.setValue)
        self.Distance_min_Slider.valueChanged['int'].connect(self.spinBox_10.setValue)
        self.spinBox_10.valueChanged['int'].connect(self.Distance_min_Slider.setValue)
        self.Distance_max_Slider.valueChanged['int'].connect(self.spinBox_11.setValue)
        self.spinBox_11.valueChanged['int'].connect(self.Distance_max_Slider.setValue)
        self.Smooth_Slider.valueChanged['int'].connect(self.spinBox_8.setValue)
        self.spinBox_8.valueChanged['int'].connect(self.Smooth_Slider.setValue)
        self.MIDI_Channel_Slider.valueChanged['int'].connect(self.spinBox_15.setValue)
        self.spinBox_15.valueChanged['int'].connect(self.MIDI_Channel_Slider.setValue)
        self.spinBox_16.valueChanged['int'].connect(self.Latency_Slider.setValue)
        self.spinBox_16.valueChanged['int'].connect(self.Latency_Slider.setValue)
        QtCore.QMetaObject.connectSlotsByName(Preferences)
        Preferences.setTabOrder(self.Refresh, self.Load_Preset)
        Preferences.setTabOrder(self.Load_Preset, self.Save)

    def retranslateUi(self, Preferences):
        _translate = QtCore.QCoreApplication.translate
        Preferences.setWindowTitle(_translate("Preferences", "CONTROL USB"))
        self.Save.setText(_translate("Preferences", "Save"))
        self.Refresh.setText(_translate("Preferences", "Refresh"))
        self.Load_Preset.setText(_translate("Preferences", "Load Preset"))
        self.Quit.setText(_translate("Preferences", "Quit"))
        self.Save_Preset.setText(_translate("Preferences", "Save Preset"))
        self.label_25.setText(_translate("Preferences", "Designed by Sasha Malkovich"))
        self.label_19.setText(_translate("Preferences", "LED Control"))
        self.label_17.setText(_translate("Preferences", "Speed"))
        self.label_16.setText(_translate("Preferences", "LED Programm"))
        self.label_18.setText(_translate("Preferences", "Brightness"))
        self.label_22.setText(_translate("Preferences", "Super Sonic Sensor Left"))
        self.COM_Ports.setText(_translate("Preferences", "CONTROL USB"))
        self.label_26.setText(_translate("Preferences", "Super Sonic Sensor Right"))
        self.label_27.setText(_translate("Preferences", "1"))
        self.label_28.setText(_translate("Preferences", "2"))
        self.label_29.setText(_translate("Preferences", "3"))
        self.label_30.setText(_translate("Preferences", "4"))
        self.label_31.setText(_translate("Preferences", "5"))
        self.Connecting.setText(_translate("Preferences", "Connecting..."))
        self.label_20.setText(_translate("Preferences", "MIDI Channel"))
        self.label_32.setText(_translate("Preferences", "Latency"))
        self.label_21.setText(_translate("Preferences", "MIDI & Latency Control"))
        self.label_23.setText(_translate("Preferences", "MIDI Controllers Assign"))
        self.Smooth_label.setText(_translate("Preferences", "Smoothing"))
        self.Distance_min_label.setText(_translate("Preferences", "Distance Min"))
        self.Distance_max_label.setText(_translate("Preferences", "Distance Max"))
        self.label_5.setText(_translate("Preferences", "Super Sonic Sensor"))
        self.label_12.setText(_translate("Preferences", "Devices ON/OFF"))
        self.SuperSonic_R_Button.setText(_translate("Preferences", " S. Sonic Right"))
        self.SuperSonic_L_Button.setText(_translate("Preferences", " S. Sonic Left"))
        self.Potentiometrs.setText(_translate("Preferences", "Potentiometers"))
        self.label_24.setText(_translate("Preferences", "Operations"))
        self.actionControllers_Setup.setText(_translate("Preferences", "Controllers Setup"))
